### ISSUE TITLE
feat: object builder - filter by object_id

### ISSUE THREAD

**Issue by frondeus** [epiphany-platform/CommonDataLayer#376]
- [x] Object builder
- [x] Partial update engine
- [ ] User materializer(direct requests from users)

**Comment by luke-biel** [comment]
How would this work? I'm already implementing some kind of filtering by object id in `edge-registry`, I'd prefer to confirm we don't duplicate a feature in stage 1 just to throw one option away in stage 2.

**Comment by Kononnable** [comment]
Object builder just passes proper request to edge-registry, it doesn't do any business logic related to filtration based on object_id (it will if filtration is based on another field). This issue is mostly for changing data formats passed between services and update request to edge repository.
(Yep, it's not really clear in the description).
