### ISSUE TITLE
Object builder and Materializer error handling

### ISSUE THREAD

**Issue by frondeus** [epiphany-platform/CommonDataLayer#543]
Both OB and MG have to send notifications to user once a row fails to build or get inserted.

**Notes:**
May require custom solution rather than notifications that we currently use in cdl.

**AC:**
* OB writes to error channel when it fails to create materialized view row
* MG writes to error channel when it fails to insert a row into target database

**Comment by Kononnable** [comment]
Depending on the user the proper reaction may be to just report errored rows and continue with the operation(if it's an error related only to some of the results) or to abort the whole process. Data produced during operations ending with fatal errors should always be rejected.

The update process in materializer should be atomic(for queried data to be integral). Transaction are a good way to achieve that, memory should not be a problem. There are two important things though which can not be forgotten - operation failure have to be  handled properly (transaction abort) and proper transaction isolation level must be used(and documented) - both on CDL and user side of things. Isolation levels are important when it comes to performance.
Typical different use cases when it comes to isolation levels:
-  it might be important for the user to get partial data as soon as possible with possibility of this data being rollbacked or not containing all of the results(e.g. read uncommited transaction isolation level).
- data might be required to be integral at all times(under some more assumptions) and always available even if it's a bit outdated(e.g. mvvc/snapshot transaction isolation level).
- Third route(synchronous change) is not possible in CDL because of asynchronous role of partial update engine and object builder.

Other then transaction there are two ways of doing it(that I can think of) without introducing too much overhead:
- use separate temporary table and single merge statement once all rows are materialized 
- add version identifier to materialized rows and require from users to limit their queries to rows inserted during already finished materialization updates. This solution however have some additional quirks when it comes to data updates/removals.

**Comment by frondeus** [comment]
One extra comment worth mentioning:

Most errors should be validated or prematurely issued before we start sending data to materializer.
Things like invalid relation type, invalid data, could be calculated before object builder starts its work.
Either when user adds new view definition, or when inserts new data to data-router (validation for it is I think scheduled for next year?). 

Nevertheless, there might be situation where invalid data is sent and corrupted to Object Builder and there should be a good equivalent of panic handling in Materializer General.

**Comment by luke-biel** [comment]
Currently blocked, need to find concrete solution/review options, discussion planned for friday, 09.07.

**Comment by luke-biel** [comment]
Changed AC to reflect discussion with team
